# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 05:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_mastery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmQuestion',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('topic', models.TextField(default='')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('techniques', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default=''), size=None)),
                ('input', models.TextField(default='')),
                ('output', models.TextField(default='')),
                ('solution', models.TextField(default='')),
                ('spaceComplexity', models.TextField(default='')),
                ('timeComplexity', models.TextField(default='')),
                ('note', models.TextField(default='')),
            ],
        ),
    ]
